version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "60080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.5.62
    ports:
      - "63306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/mysql_data:/var/lib/mysql
    env_file:
      - ./docker/db/db-variables.env

  dockerphpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "64040:80"
    links:
      - db
    env_file:
      - ./docker/db/db-variables.env
